services:
  - type: web
    name: chatloop
    env: python
    buildCommand: "pip install -r ChatLoop/requirements.txt"
    startCommand: "python ChatLoop/app.py"
    region: singapore
    plan: free
